Criado um CMakeLists.txt
hpc-fci-mackenzie/FlakyBuild pull request #7
Opened 2020-09-03 14:14 UTC by TsunekiR

2020-09-03 14:28 UTC, calebepb requested changes

2020-09-03 14:28 UTC, calebepb commented on CMakeLists.txt
> +set(THREADS_PREFER_PTHREAD_FLAG ON)
Adicionar antes: `set(CMAKE_THREAD_PREFER_PTHREAD TRUE)`

2020-09-03 14:30 UTC, calebepb requested changes

2020-09-03 14:30 UTC, calebepb commented on CMakeLists.txt
> +set(THREADS_PREFER_PTHREAD_FLAG ON)
Mudar de `ON` para `TRUE`

2020-09-03 14:35 UTC, TsunekiR commented on CMakeLists.txt
> +set(THREADS_PREFER_PTHREAD_FLAG ON)
feito!

2020-09-10 14:50 UTC, calebepb requested changes

2020-09-10 14:50 UTC, calebepb commented on CMakeLists.txt
> +set(THREADS_PREFER_PTHREAD_FLAG TRUE)
Eu havia anotado para usar também o `set(CMAKE_THREAD_PREFER_PTHREAD TRUE)`
Algum motivo para a gente ter decidido não colocá-lo?

2020-09-10 14:53 UTC, calebepb commented
Aproveita e adicionar no `.gitignore` uma regra para nao adicionar `.swp`...

2020-09-18 16:08 UTC, calebepb approved these changes

2020-09-18 16:09 UTC, calebepb commented
Close #2

2020-09-18 16:10 UTC, merged